TrajectoryPlannerROS:

    # Robot Configuration Parameters
    acc_lim_x: 2.0
    acc_lim_y: 0.0
    acc_lim_theta: 3.0

    max_vel_x: 0.5
    min_vel_x: 0.1

    max_vel_y: 0.0
    min_vel_y: 0.0

    max_vel_theta: 1.0
    min_vel_theta: -1.0
    max_rotational_vel: 1.0
    min_in_place_rotational_vel: 0.2

    escape_vel: -0.1
    holonomic_robot: false

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.1
    latch_xy_goal_tolerance: false

    # Forward Simulation Parameters
    sim_time: 1.5
    sim_granularity: 0.02
    angular_sim_granularity: 0.02
    vx_samples: 6
    vtheta_samples: 20
    controller_frequency: 20

    # Trajectory Scoring Parameters
    meter_scoring: true 
    occdist_scale:  0.1
    pdist_scale: 1.5
    gdist_scale: 0.8

    heading_lookahead: 0.30
    heading_scoring: false
    heading_scoring_timestep: 0.8
    dwa: true
    simple_attractor: false
    publish_cost_grid_pc: true

    #Oscillation Prevention Parameters
    oscillation_reset_dist: 0.25
    escape_reset_dist: 0.1
    escape_reset_theta: 0.1
