TebLocalPlannerROS:
odom_topic: /odom
map_frame: /map
# Trajectory
teb_autosize: True
dt_ref: 0.4
dt_hysteresis: 0.1
global_plan_overwrite_orientation: True
max_global_plan_lookahead_dist: 3.0
feasibility_check_no_poses: 2
allow_init_backward_motion: false
# Robot
max_vel_x: 0.4
max_vel_x_backwards: 0.2
max_vel_theta: 0.3 # the angular velocity is also bounded by min_turning_radius in case of a carlike robot (r = v / omega)

acc_lim_x: 0.5
acc_lim_theta: 0.5
# ***************** Carlike robot parameters ********************
min_turning_radius: 2.7
 # Min turning radius of the carlike  robot (compute value using a model or adjust with rqt_reconfigure manually)
wheelbase: 0.41
 # Wheelbase of our robo
