read_rate: 15
write_rate: 25
controller_type: phidget
dynamixels: {
    shoulder: {id: 0, max_angle: 150, min_angle: -150, max_speed: 90},
    elbow: {id: 1, max_angle: 150, min_angle: -150, max_speed: 90},
    wrist_flex: {id: 2, max_angle: 100, min_angle: -100, max_speed: 90},
    gripper: {id: 3, max_speed: 90},
}
controllers: {
    arm_controller: {type: follow_controller, joints: [shoulder, elbow, wrist_flex], onboard: False }
}
